# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/event.proto
# Protobuf Python Version: 5.29.0-rc3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '-rc3',
    'proto/event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/event.proto\x12\x14HikStreamPluginsDump\"\x7f\n\tEventDump\x12\x36\n\x0b\x65ventConfig\x18\x01 \x02(\x0b\x32!.HikStreamPluginsDump.EventConfig\x12:\n\reventMetaData\x18\x02 \x02(\x0b\x32#.HikStreamPluginsDump.EventMetaData\"e\n\x0b\x45ventConfig\x12\x15\n\rextendLibPath\x18\x02 \x01(\t\x12\x15\n\rextendLibDesc\x18\x03 \x01(\t\x12\x12\n\ncustomRule\x18\x04 \x01(\t\x12\x14\n\x0cpipelineName\x18\x05 \x02(\t\"\xb0\x01\n\rEventMetaData\x12\r\n\x05index\x18\x01 \x02(\x05\x12\x11\n\tmediaType\x18\x02 \x02(\r\x12\x11\n\tframeType\x18\x03 \x02(\r\x12\x11\n\ttimeStamp\x18\x04 \x02(\r\x12\r\n\x05\x61larm\x18\x05 \x02(\r\x12\x19\n\x11uploadAlarmCenter\x18\x06 \x02(\r\x12\x16\n\x0e\x61larmImagePath\x18\x07 \x02(\x0c\x12\x15\n\ralarmJsonData\x18\x08 \x01(\tB-\n\x1e\x63om.hikvision.bsp.parser.protoB\x0b\x45ventDumpPB')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.hikvision.bsp.parser.protoB\013EventDumpPB'
  _globals['_EVENTDUMP']._serialized_start=43
  _globals['_EVENTDUMP']._serialized_end=170
  _globals['_EVENTCONFIG']._serialized_start=172
  _globals['_EVENTCONFIG']._serialized_end=273
  _globals['_EVENTMETADATA']._serialized_start=276
  _globals['_EVENTMETADATA']._serialized_end=452
# @@protoc_insertion_point(module_scope)
