# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/file.proto
# Protobuf Python Version: 5.29.0-rc3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '-rc3',
    'proto/file.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/file.proto\x12\x14HikStreamPluginsDump\"z\n\x08\x46ileDump\x12\x34\n\nfileConfig\x18\x01 \x02(\x0b\x32 .HikStreamPluginsDump.FileConfig\x12\x38\n\x0c\x66ileMetaData\x18\x02 \x02(\x0b\x32\".HikStreamPluginsDump.FileMetaData\"\xeb\x01\n\nFileConfig\x12\x12\n\nstorageDir\x18\x01 \x02(\t\x12\x13\n\x0bvideoFormat\x18\x02 \x02(\t\x12\x14\n\x0cvideoMaxSize\x18\x03 \x02(\x05\x12\x15\n\rvideoDuration\x18\x04 \x02(\x05\x12\x16\n\x0e\x62\x65\x66oreDuration\x18\x05 \x02(\x05\x12\x15\n\rafterDuration\x18\x06 \x02(\x05\x12\x12\n\nprefixName\x18\x07 \x02(\t\x12\x0e\n\x06record\x18\x08 \x02(\t\x12\x1e\n\x16\x62\x61\x63kgroundImageCapture\x18\t \x02(\t\x12\x14\n\x0cpipelineName\x18\n \x02(\t\"\xe3\x01\n\x0c\x46ileMetaData\x12\r\n\x05index\x18\x01 \x02(\x05\x12\x11\n\tmediaType\x18\x02 \x02(\r\x12\x11\n\tframeType\x18\x03 \x02(\r\x12\x11\n\ttimeStamp\x18\x04 \x02(\r\x12\r\n\x05\x61larm\x18\x05 \x02(\r\x12\x11\n\tframeData\x18\x06 \x02(\x0c\x12\x1b\n\x13\x62\x61\x63kgroundImageData\x18\x07 \x01(\x0c\x12\x16\n\x0e\x61larmImageData\x18\x08 \x01(\x0c\x12\x0f\n\x07\x65ventId\x18\t \x01(\r\x12\x13\n\x0b\x61nalyzeType\x18\n \x01(\r\x12\x0e\n\x06record\x18\x0b \x01(\tB,\n\x1e\x63om.hikvision.bsp.parser.protoB\nFileDumpPB')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.file_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.hikvision.bsp.parser.protoB\nFileDumpPB'
  _globals['_FILEDUMP']._serialized_start=42
  _globals['_FILEDUMP']._serialized_end=164
  _globals['_FILECONFIG']._serialized_start=167
  _globals['_FILECONFIG']._serialized_end=402
  _globals['_FILEMETADATA']._serialized_start=405
  _globals['_FILEMETADATA']._serialized_end=632
# @@protoc_insertion_point(module_scope)
