# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/forward.proto
# Protobuf Python Version: 5.29.0-rc3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '-rc3',
    'proto/forward.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/forward.proto\x12\x14HikStreamPluginsDump\"\xd1\x01\n\x0b\x46orwardDump\x12:\n\rforwardConfig\x18\x01 \x02(\x0b\x32#.HikStreamPluginsDump.ForwardConfig\x12\x46\n\x13\x66orwardStreamConfig\x18\x02 \x02(\x0b\x32).HikStreamPluginsDump.ForwardStreamConfig\x12>\n\x0f\x66orwardMetaData\x18\x03 \x02(\x0b\x32%.HikStreamPluginsDump.ForwardMetaData\"[\n\rForwardConfig\x12\x10\n\x08httpPort\x18\x01 \x02(\x05\x12\x10\n\x08rtspPort\x18\x02 \x02(\x05\x12\x10\n\x08rtmpPort\x18\x03 \x02(\x05\x12\x14\n\x0cpipelineName\x18\x04 \x02(\t\"u\n\x13\x46orwardStreamConfig\x12\x12\n\nhttpEnable\x18\x01 \x02(\x05\x12\x12\n\nrtspEnable\x18\x02 \x02(\x05\x12\x0e\n\x06status\x18\x03 \x02(\t\x12\x0b\n\x03uri\x18\x04 \x02(\t\x12\x0c\n\x04user\x18\x05 \x02(\t\x12\x0b\n\x03pwd\x18\x06 \x02(\t\"\x9c\x01\n\x0f\x46orwardMetaData\x12\r\n\x05index\x18\x01 \x02(\x05\x12\x11\n\tmediaType\x18\x02 \x02(\r\x12\x11\n\tframeType\x18\x03 \x02(\r\x12\x11\n\ttimeStamp\x18\x04 \x02(\r\x12\x11\n\terrorCode\x18\x05 \x02(\r\x12\x11\n\tframeData\x18\x06 \x01(\x0c\x12\x1b\n\x13\x62\x61\x63kgroundImageData\x18\x07 \x01(\x0c\x42/\n\x1e\x63om.hikvision.bsp.parser.protoB\rForwardDumpPB')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.forward_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.hikvision.bsp.parser.protoB\rForwardDumpPB'
  _globals['_FORWARDDUMP']._serialized_start=46
  _globals['_FORWARDDUMP']._serialized_end=255
  _globals['_FORWARDCONFIG']._serialized_start=257
  _globals['_FORWARDCONFIG']._serialized_end=348
  _globals['_FORWARDSTREAMCONFIG']._serialized_start=350
  _globals['_FORWARDSTREAMCONFIG']._serialized_end=467
  _globals['_FORWARDMETADATA']._serialized_start=470
  _globals['_FORWARDMETADATA']._serialized_end=626
# @@protoc_insertion_point(module_scope)
